"""rename address

Revision ID: 510f1db55515
Revises: af57c5c37fb7
Create Date: 2024-05-13 15:58:37.319527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510f1db55515'
down_revision = 'af57c5c37fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
